version: 0.2
env:
  shell: bash
  variables:
    AWS_DEFAULT_REGION: "us-east-1"
    ECR_REPO_URI: "935873185508.dkr.ecr.us-east-1.amazonaws.com/coworking-analytics"

phases:
  pre_build:
    commands:
      - echo "Login to ECR..."
      - aws ecr get-login-password --region "$AWS_DEFAULT_REGION" \
          | docker login --username AWS --password-stdin "${ECR_REPO_URI%/*}"
      - IMAGE_TAG="${IMAGE_TAG_PREFIX:-build}-${CODEBUILD_BUILD_NUMBER}"
      - echo "Tag: $IMAGE_TAG"

  build:
    commands:
      - echo "Build image from analytics/"
      - cd analytics
      - docker build -t "$ECR_REPO_URI:$IMAGE_TAG" -t "$ECR_REPO_URI:latest" .

  post_build:
    commands:
      - echo "Push to ECR..."
      - docker push "$ECR_REPO_URI:$IMAGE_TAG"
      - docker push "$ECR_REPO_URI:latest"
      - printf '{"imageUri":"%s","tag":"%s"}\n' "$ECR_REPO_URI" "$IMAGE_TAG" > image_detail.json

artifacts:
  files:
    - image_detail.json